### ISSUE TITLE
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'java': was expecting ('true', 'false' or 'null')

### ISSUE THREAD

**Issue by slecholineas** [bjansen/swagger-schema-validator#8]
When I try to validate 
[cis-assignment-74882.json.txt](https://github.com/bjansen/swagger-schema-validator/files/4820211/cis-assignment-74882.json.txt) with 
[Assignments-v3.0.7.yaml.txt](https://github.com/bjansen/swagger-schema-validator/files/4820209/Assignments-v3.0.7.yaml.txt) and definition "/definitions/assignment", 
I'm getting the following error: "com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'java': was expecting ('true', 'false' or 'null')". Any idea how this can be solved ?

```
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'java': was expecting ('true', 'false' or 'null')
 at [Source: (String)"java.io.FileInputStream@dc9876b"; line: 1, column: 5]

	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:673)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2835)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1889)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:747)
	at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4030)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2539)
	at com.github.bjansen.ssv.SwaggerValidator.validate(SwaggerValidator.java:88)
	at com.github.bjansen.ssv.SwaggerValidator.validate(SwaggerValidator.java:81)
```

**Comment by bjansen** [comment]
I can't reproduce the problem. It looks like your JSON file is not exactly the same as the one you attached here, and contains `java` on line 1, column 5. Is that possible?

**Comment by bjansen** [comment]
Well I have a validation error, but no exception:

```
error: object has missing required properties (["createdBy"])
    level: "error"
    schema: {"loadingURI":"#","pointer":"/definitions/assignment"}
    instance: {"pointer":""}
    domain: "validation"
    keyword: "required"
    required: ["actions","createdBy","createdOn","id","statusId","statusTransitionOn","type"]
    missing: ["createdBy"]
```

**Comment by slecholineas** [comment]
Is this code the correct code to parse the YAML and JSON files:
`final InputStreamReader swaggerSpec = new InputStreamReader(new FileInputStream(new File(yaml)));
        SwaggerValidator validator = SwaggerValidator.forYamlSchema(swaggerSpec);
        final FileInputStream obj = new FileInputStream(new File(json));
        ProcessingReport report = validator.validate(String.valueOf(obj),definition);
        return report;`

**Comment by slecholineas** [comment]
I've changed the implementation to use
`IOUtils.toString(obj, StandardCharsets.UTF_8)`
and now I'm getting the validation error.

**Comment by bjansen** [comment]
Right, `String.valueOf(obj)` is actually `obj.toString()`, which gives something like `java.io.FileInputStream@5b464ce8` instead of the actual file content.
